global:
  datacenter: dc1
  tls:
    enabled: true
  federation:
    enabled: true
    createFederationSecret: true
  name: consul

ui:
  enabled: true
  service:
    type: 'NodePort'
    ports:
      nodePort: 18500

server:
    replicas: 1

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
  enableHealthChecks: false
  replicas: 1
  service:
    enabled: true
    type: 'NodePort'
    nodePort: 30001