# Choose an optional name for the datacenter
global:
  name: consul
  datacenter: dc1
  
# Enable the Consul Web UI via a NodePort
ui:
  enabled: true
  service:
    type: 'NodePort'
    ports:
      nodePort: 18500
  
# Enable Connect for secure communication between nodes
connectInject:
  enabled: true

controller:
  enabled: true
  
# Use only one Consul server for local development
server:
  replicas: 1
